### ISSUE TITLE
Timebox the review process for charters and RFCs

### ISSUE THREAD

**Issue by tburdett** [HumanCellAtlas/dcp-community#29]
There have been a number of proposed charters created at the same time, and it seems to me that adding a time frame for reviews (for both charters and RFCs) is needed. The process of assigning reviewers and soliciting feedback seems to have worked inconsistently too. 

The charter process currently says:
> Feedback is added to the pull request comment thread by community members. 

I would suggest the following modifications for authors:

1. Assign key reviewers, including PMs of impacted/dependant charters
2. Add a deadline for community review comments
3. Send reminders to the #dcp slack channel and to assigned key reviewers directly shortly before the community review deadline

Appropriate timeframes, based on the first round of charter reviews, would seem to be ~1 month for (2) and maybe 3 days for (3).

**Comment by brianraymor** [comment]
A timebox is a great idea. I would be concerned about ~1 month - because the tendency might be for all the comments to arrive on the last day. We're currently seeing this behavior with the final-reviews. 

Rust is free-form with its community review (_At some point, a member of the subteam will propose a "motion for final comment period"_) but then uses a 10 business day deadline for its final review.

How about:

1. 2 weeks minimum for community review and assigned reviewers
2. 1 week minimum for final review

I also don't know whether we would want different minimums for charters and RFCs?

**Comment by tburdett** [comment]
Agreed, I proposed 1 month based on the average charter throughput but it does seem unduly long. 2 weeks followed by 1 week seems entirely sensible to me

**Comment by brianraymor** [comment]
**Notes from PM F2F (9/25/18):**

Both the charters and RFC processes will be updated with specific guidance.

*Charters:*
- 2 weeks: charter-community-review
- 1 week [or less]: author completes edits
- 1 week: charter-oversight-review - only approvers can review
- IF only copy edits -> charter-approved
- IF substantial changes are required -> charter-community-review

*RFCs:*
- N weeks: rfc-community-review - where *N* is assigned by *Oversight* based on severity of change
- 2 weeks [in parallel to rfc-community-review] IF science-review-required
- 1 week [after rfc-community-review and science-review-complete]: author completes edits
- 1 week rfc-oversight-review - only approvers can review
- IF only copy edits -> rfc-approved
- IF substantial changes are required -> rfc-community-review

The _last call_ dates_ must be included in the review announcements to dcp and the oversight teams.

Based on a conversation with @sampierson and @mweiden - also ensure that the top-level summary in the PR includes the last call date.

**Comment by brianraymor** [comment]
@HumanCellAtlas/dcp-pm-team - regarding:

*RFCs:*
- N weeks: rfc-community-review - where *N* is assigned by *Oversight* based on severity of change

 I think that this overcomplicates and slows down the process - PM has to assign a shepherd. Oversight has to assign a _last call_ date. Days pass. I propose to use a 2 week _last call_ for community review which may be extended by *Oversight*. Comments?
