### ISSUE TITLE
Plan Beta test hackathon at CZI

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/dcp-community#64]
@kozbo commented on [Tue Oct 16 2018](https://github.com/HumanCellAtlas/dcp/issues/171)

**Comment by kozbo** [comment]
@adriennes should we abandon the plan for a hackathon with beta participants? Could we do it towards the end of Beta 2?

**Comment by adriennes** [comment]
I'm still unsure what we mean by this hackathon.  I think we need to define it a bit more clearly.  In my mind, I would rather wait til we get into Beta 2 and then decide whether a hackathon seems like the right approach (and if so, what the structure should be) rather than define it now.

**Comment by lauraclarke** [comment]
To give some historical context, this was proposed by members of the GG when the timeframe between the testing starting and our February F2F seems more reasonable. The idea was to get people who wanted to use the system in the same room as the devs to see the ups and downs of interacting with the system.

This never quite played out so I think it is totally fine to close this ticket. Depending on how you are tracking things either people remembering that some sort of F2F meeting with users and devs in the same room or putting in a ticket to assess say post cbeta 2 if doing this would be a good idea would be fine.
